// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32         `json:"id"`
	PostID    int32         `json:"post_id"`
	UserEmail string        `json:"user_email"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ParentID  sql.NullInt32 `json:"parent_id"`
}

type Post struct {
	ID          int32     `json:"id"`
	AuthorEmail string    `json:"author_email"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
