BEGIN;

CREATE TABLE IF NOT EXISTS comments (
    id SERIAL  PRIMARY KEY,
    post_id INTEGER NOT NULL ,
    user_email VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);

COMMIT;